/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.Argument1;
import org.xtext.example.myDsl.ArrayC;
import org.xtext.example.myDsl.ClassVariable;
import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.ObjectC;
import org.xtext.example.myDsl.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Argument1</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getInteger <em>Integer</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getFloatValue <em>Float Value</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getClassVariable <em>Class Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getObjectC <em>Object C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.Argument1Impl#getArrayC <em>Array C</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Argument1Impl extends MinimalEObjectImpl.Container implements Argument1
{
  /**
   * The default value of the '{@link #getInteger() <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger()
   * @generated
   * @ordered
   */
  protected static final int INTEGER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInteger() <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger()
   * @generated
   * @ordered
   */
  protected int integer = INTEGER_EDEFAULT;

  /**
   * The cached value of the '{@link #getFloatValue() <em>Float Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloatValue()
   * @generated
   * @ordered
   */
  protected org.xtext.example.myDsl.Float floatValue;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * The cached value of the '{@link #getClassVariable() <em>Class Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassVariable()
   * @generated
   * @ordered
   */
  protected ClassVariable classVariable;

  /**
   * The cached value of the '{@link #getVariable() <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable()
   * @generated
   * @ordered
   */
  protected Variable variable;

  /**
   * The cached value of the '{@link #getObjectC() <em>Object C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectC()
   * @generated
   * @ordered
   */
  protected ObjectC objectC;

  /**
   * The cached value of the '{@link #getArrayC() <em>Array C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrayC()
   * @generated
   * @ordered
   */
  protected ArrayC arrayC;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Argument1Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ARGUMENT1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInteger()
  {
    return integer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteger(int newInteger)
  {
    int oldInteger = integer;
    integer = newInteger;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__INTEGER, oldInteger, integer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.example.myDsl.Float getFloatValue()
  {
    return floatValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFloatValue(org.xtext.example.myDsl.Float newFloatValue, NotificationChain msgs)
  {
    org.xtext.example.myDsl.Float oldFloatValue = floatValue;
    floatValue = newFloatValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__FLOAT_VALUE, oldFloatValue, newFloatValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFloatValue(org.xtext.example.myDsl.Float newFloatValue)
  {
    if (newFloatValue != floatValue)
    {
      NotificationChain msgs = null;
      if (floatValue != null)
        msgs = ((InternalEObject)floatValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__FLOAT_VALUE, null, msgs);
      if (newFloatValue != null)
        msgs = ((InternalEObject)newFloatValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__FLOAT_VALUE, null, msgs);
      msgs = basicSetFloatValue(newFloatValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__FLOAT_VALUE, newFloatValue, newFloatValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassVariable getClassVariable()
  {
    return classVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClassVariable(ClassVariable newClassVariable, NotificationChain msgs)
  {
    ClassVariable oldClassVariable = classVariable;
    classVariable = newClassVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__CLASS_VARIABLE, oldClassVariable, newClassVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClassVariable(ClassVariable newClassVariable)
  {
    if (newClassVariable != classVariable)
    {
      NotificationChain msgs = null;
      if (classVariable != null)
        msgs = ((InternalEObject)classVariable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__CLASS_VARIABLE, null, msgs);
      if (newClassVariable != null)
        msgs = ((InternalEObject)newClassVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__CLASS_VARIABLE, null, msgs);
      msgs = basicSetClassVariable(newClassVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__CLASS_VARIABLE, newClassVariable, newClassVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable getVariable()
  {
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariable(Variable newVariable, NotificationChain msgs)
  {
    Variable oldVariable = variable;
    variable = newVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__VARIABLE, oldVariable, newVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariable(Variable newVariable)
  {
    if (newVariable != variable)
    {
      NotificationChain msgs = null;
      if (variable != null)
        msgs = ((InternalEObject)variable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__VARIABLE, null, msgs);
      if (newVariable != null)
        msgs = ((InternalEObject)newVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__VARIABLE, null, msgs);
      msgs = basicSetVariable(newVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__VARIABLE, newVariable, newVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObjectC getObjectC()
  {
    return objectC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObjectC(ObjectC newObjectC, NotificationChain msgs)
  {
    ObjectC oldObjectC = objectC;
    objectC = newObjectC;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__OBJECT_C, oldObjectC, newObjectC);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObjectC(ObjectC newObjectC)
  {
    if (newObjectC != objectC)
    {
      NotificationChain msgs = null;
      if (objectC != null)
        msgs = ((InternalEObject)objectC).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__OBJECT_C, null, msgs);
      if (newObjectC != null)
        msgs = ((InternalEObject)newObjectC).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__OBJECT_C, null, msgs);
      msgs = basicSetObjectC(newObjectC, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__OBJECT_C, newObjectC, newObjectC));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArrayC getArrayC()
  {
    return arrayC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetArrayC(ArrayC newArrayC, NotificationChain msgs)
  {
    ArrayC oldArrayC = arrayC;
    arrayC = newArrayC;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__ARRAY_C, oldArrayC, newArrayC);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArrayC(ArrayC newArrayC)
  {
    if (newArrayC != arrayC)
    {
      NotificationChain msgs = null;
      if (arrayC != null)
        msgs = ((InternalEObject)arrayC).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__ARRAY_C, null, msgs);
      if (newArrayC != null)
        msgs = ((InternalEObject)newArrayC).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ARGUMENT1__ARRAY_C, null, msgs);
      msgs = basicSetArrayC(newArrayC, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARGUMENT1__ARRAY_C, newArrayC, newArrayC));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT1__FLOAT_VALUE:
        return basicSetFloatValue(null, msgs);
      case MyDslPackage.ARGUMENT1__CLASS_VARIABLE:
        return basicSetClassVariable(null, msgs);
      case MyDslPackage.ARGUMENT1__VARIABLE:
        return basicSetVariable(null, msgs);
      case MyDslPackage.ARGUMENT1__OBJECT_C:
        return basicSetObjectC(null, msgs);
      case MyDslPackage.ARGUMENT1__ARRAY_C:
        return basicSetArrayC(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT1__INTEGER:
        return getInteger();
      case MyDslPackage.ARGUMENT1__FLOAT_VALUE:
        return getFloatValue();
      case MyDslPackage.ARGUMENT1__STRING:
        return getString();
      case MyDslPackage.ARGUMENT1__CLASS_VARIABLE:
        return getClassVariable();
      case MyDslPackage.ARGUMENT1__VARIABLE:
        return getVariable();
      case MyDslPackage.ARGUMENT1__OBJECT_C:
        return getObjectC();
      case MyDslPackage.ARGUMENT1__ARRAY_C:
        return getArrayC();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT1__INTEGER:
        setInteger((Integer)newValue);
        return;
      case MyDslPackage.ARGUMENT1__FLOAT_VALUE:
        setFloatValue((org.xtext.example.myDsl.Float)newValue);
        return;
      case MyDslPackage.ARGUMENT1__STRING:
        setString((String)newValue);
        return;
      case MyDslPackage.ARGUMENT1__CLASS_VARIABLE:
        setClassVariable((ClassVariable)newValue);
        return;
      case MyDslPackage.ARGUMENT1__VARIABLE:
        setVariable((Variable)newValue);
        return;
      case MyDslPackage.ARGUMENT1__OBJECT_C:
        setObjectC((ObjectC)newValue);
        return;
      case MyDslPackage.ARGUMENT1__ARRAY_C:
        setArrayC((ArrayC)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT1__INTEGER:
        setInteger(INTEGER_EDEFAULT);
        return;
      case MyDslPackage.ARGUMENT1__FLOAT_VALUE:
        setFloatValue((org.xtext.example.myDsl.Float)null);
        return;
      case MyDslPackage.ARGUMENT1__STRING:
        setString(STRING_EDEFAULT);
        return;
      case MyDslPackage.ARGUMENT1__CLASS_VARIABLE:
        setClassVariable((ClassVariable)null);
        return;
      case MyDslPackage.ARGUMENT1__VARIABLE:
        setVariable((Variable)null);
        return;
      case MyDslPackage.ARGUMENT1__OBJECT_C:
        setObjectC((ObjectC)null);
        return;
      case MyDslPackage.ARGUMENT1__ARRAY_C:
        setArrayC((ArrayC)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT1__INTEGER:
        return integer != INTEGER_EDEFAULT;
      case MyDslPackage.ARGUMENT1__FLOAT_VALUE:
        return floatValue != null;
      case MyDslPackage.ARGUMENT1__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
      case MyDslPackage.ARGUMENT1__CLASS_VARIABLE:
        return classVariable != null;
      case MyDslPackage.ARGUMENT1__VARIABLE:
        return variable != null;
      case MyDslPackage.ARGUMENT1__OBJECT_C:
        return objectC != null;
      case MyDslPackage.ARGUMENT1__ARRAY_C:
        return arrayC != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (integer: ");
    result.append(integer);
    result.append(", string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //Argument1Impl
