/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.CssValue;
import org.xtext.example.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Css Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getInteger <em>Integer</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getComa <em>Coma</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getApostrophe <em>Apostrophe</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getHashtag <em>Hashtag</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.CssValueImpl#getPourcent <em>Pourcent</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CssValueImpl extends MinimalEObjectImpl.Container implements CssValue
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * The default value of the '{@link #getInteger() <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger()
   * @generated
   * @ordered
   */
  protected static final int INTEGER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInteger() <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInteger()
   * @generated
   * @ordered
   */
  protected int integer = INTEGER_EDEFAULT;

  /**
   * The default value of the '{@link #getComa() <em>Coma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComa()
   * @generated
   * @ordered
   */
  protected static final String COMA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getComa() <em>Coma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComa()
   * @generated
   * @ordered
   */
  protected String coma = COMA_EDEFAULT;

  /**
   * The default value of the '{@link #getApostrophe() <em>Apostrophe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApostrophe()
   * @generated
   * @ordered
   */
  protected static final String APOSTROPHE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getApostrophe() <em>Apostrophe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApostrophe()
   * @generated
   * @ordered
   */
  protected String apostrophe = APOSTROPHE_EDEFAULT;

  /**
   * The default value of the '{@link #getHashtag() <em>Hashtag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHashtag()
   * @generated
   * @ordered
   */
  protected static final String HASHTAG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHashtag() <em>Hashtag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHashtag()
   * @generated
   * @ordered
   */
  protected String hashtag = HASHTAG_EDEFAULT;

  /**
   * The default value of the '{@link #getPourcent() <em>Pourcent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPourcent()
   * @generated
   * @ordered
   */
  protected static final String POURCENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPourcent() <em>Pourcent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPourcent()
   * @generated
   * @ordered
   */
  protected String pourcent = POURCENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CssValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CSS_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInteger()
  {
    return integer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInteger(int newInteger)
  {
    int oldInteger = integer;
    integer = newInteger;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__INTEGER, oldInteger, integer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getComa()
  {
    return coma;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComa(String newComa)
  {
    String oldComa = coma;
    coma = newComa;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__COMA, oldComa, coma));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getApostrophe()
  {
    return apostrophe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setApostrophe(String newApostrophe)
  {
    String oldApostrophe = apostrophe;
    apostrophe = newApostrophe;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__APOSTROPHE, oldApostrophe, apostrophe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHashtag()
  {
    return hashtag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHashtag(String newHashtag)
  {
    String oldHashtag = hashtag;
    hashtag = newHashtag;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__HASHTAG, oldHashtag, hashtag));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPourcent()
  {
    return pourcent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPourcent(String newPourcent)
  {
    String oldPourcent = pourcent;
    pourcent = newPourcent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CSS_VALUE__POURCENT, oldPourcent, pourcent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CSS_VALUE__NAME:
        return getName();
      case MyDslPackage.CSS_VALUE__STRING:
        return getString();
      case MyDslPackage.CSS_VALUE__INTEGER:
        return getInteger();
      case MyDslPackage.CSS_VALUE__COMA:
        return getComa();
      case MyDslPackage.CSS_VALUE__APOSTROPHE:
        return getApostrophe();
      case MyDslPackage.CSS_VALUE__HASHTAG:
        return getHashtag();
      case MyDslPackage.CSS_VALUE__POURCENT:
        return getPourcent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CSS_VALUE__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.CSS_VALUE__STRING:
        setString((String)newValue);
        return;
      case MyDslPackage.CSS_VALUE__INTEGER:
        setInteger((Integer)newValue);
        return;
      case MyDslPackage.CSS_VALUE__COMA:
        setComa((String)newValue);
        return;
      case MyDslPackage.CSS_VALUE__APOSTROPHE:
        setApostrophe((String)newValue);
        return;
      case MyDslPackage.CSS_VALUE__HASHTAG:
        setHashtag((String)newValue);
        return;
      case MyDslPackage.CSS_VALUE__POURCENT:
        setPourcent((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CSS_VALUE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__STRING:
        setString(STRING_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__INTEGER:
        setInteger(INTEGER_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__COMA:
        setComa(COMA_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__APOSTROPHE:
        setApostrophe(APOSTROPHE_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__HASHTAG:
        setHashtag(HASHTAG_EDEFAULT);
        return;
      case MyDslPackage.CSS_VALUE__POURCENT:
        setPourcent(POURCENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CSS_VALUE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.CSS_VALUE__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
      case MyDslPackage.CSS_VALUE__INTEGER:
        return integer != INTEGER_EDEFAULT;
      case MyDslPackage.CSS_VALUE__COMA:
        return COMA_EDEFAULT == null ? coma != null : !COMA_EDEFAULT.equals(coma);
      case MyDslPackage.CSS_VALUE__APOSTROPHE:
        return APOSTROPHE_EDEFAULT == null ? apostrophe != null : !APOSTROPHE_EDEFAULT.equals(apostrophe);
      case MyDslPackage.CSS_VALUE__HASHTAG:
        return HASHTAG_EDEFAULT == null ? hashtag != null : !HASHTAG_EDEFAULT.equals(hashtag);
      case MyDslPackage.CSS_VALUE__POURCENT:
        return POURCENT_EDEFAULT == null ? pourcent != null : !POURCENT_EDEFAULT.equals(pourcent);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", string: ");
    result.append(string);
    result.append(", integer: ");
    result.append(integer);
    result.append(", coma: ");
    result.append(coma);
    result.append(", apostrophe: ");
    result.append(apostrophe);
    result.append(", hashtag: ");
    result.append(hashtag);
    result.append(", pourcent: ");
    result.append(pourcent);
    result.append(')');
    return result.toString();
  }

} //CssValueImpl
