/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.Conditional;
import org.xtext.example.myDsl.ElementBuild;
import org.xtext.example.myDsl.Loop;
import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.Page;
import org.xtext.example.myDsl.VariableD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Build</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.ElementBuildImpl#getVariableD <em>Variable D</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.ElementBuildImpl#getPage <em>Page</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.ElementBuildImpl#getLoop <em>Loop</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.ElementBuildImpl#getConditional <em>Conditional</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElementBuildImpl extends MinimalEObjectImpl.Container implements ElementBuild
{
  /**
   * The cached value of the '{@link #getVariableD() <em>Variable D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariableD()
   * @generated
   * @ordered
   */
  protected VariableD variableD;

  /**
   * The cached value of the '{@link #getPage() <em>Page</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPage()
   * @generated
   * @ordered
   */
  protected Page page;

  /**
   * The cached value of the '{@link #getLoop() <em>Loop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoop()
   * @generated
   * @ordered
   */
  protected Loop loop;

  /**
   * The cached value of the '{@link #getConditional() <em>Conditional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditional()
   * @generated
   * @ordered
   */
  protected Conditional conditional;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementBuildImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ELEMENT_BUILD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableD getVariableD()
  {
    return variableD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariableD(VariableD newVariableD, NotificationChain msgs)
  {
    VariableD oldVariableD = variableD;
    variableD = newVariableD;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__VARIABLE_D, oldVariableD, newVariableD);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariableD(VariableD newVariableD)
  {
    if (newVariableD != variableD)
    {
      NotificationChain msgs = null;
      if (variableD != null)
        msgs = ((InternalEObject)variableD).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__VARIABLE_D, null, msgs);
      if (newVariableD != null)
        msgs = ((InternalEObject)newVariableD).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__VARIABLE_D, null, msgs);
      msgs = basicSetVariableD(newVariableD, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__VARIABLE_D, newVariableD, newVariableD));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Page getPage()
  {
    return page;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPage(Page newPage, NotificationChain msgs)
  {
    Page oldPage = page;
    page = newPage;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__PAGE, oldPage, newPage);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPage(Page newPage)
  {
    if (newPage != page)
    {
      NotificationChain msgs = null;
      if (page != null)
        msgs = ((InternalEObject)page).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__PAGE, null, msgs);
      if (newPage != null)
        msgs = ((InternalEObject)newPage).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__PAGE, null, msgs);
      msgs = basicSetPage(newPage, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__PAGE, newPage, newPage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Loop getLoop()
  {
    return loop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLoop(Loop newLoop, NotificationChain msgs)
  {
    Loop oldLoop = loop;
    loop = newLoop;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__LOOP, oldLoop, newLoop);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoop(Loop newLoop)
  {
    if (newLoop != loop)
    {
      NotificationChain msgs = null;
      if (loop != null)
        msgs = ((InternalEObject)loop).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__LOOP, null, msgs);
      if (newLoop != null)
        msgs = ((InternalEObject)newLoop).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__LOOP, null, msgs);
      msgs = basicSetLoop(newLoop, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__LOOP, newLoop, newLoop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Conditional getConditional()
  {
    return conditional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConditional(Conditional newConditional, NotificationChain msgs)
  {
    Conditional oldConditional = conditional;
    conditional = newConditional;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__CONDITIONAL, oldConditional, newConditional);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConditional(Conditional newConditional)
  {
    if (newConditional != conditional)
    {
      NotificationChain msgs = null;
      if (conditional != null)
        msgs = ((InternalEObject)conditional).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__CONDITIONAL, null, msgs);
      if (newConditional != null)
        msgs = ((InternalEObject)newConditional).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ELEMENT_BUILD__CONDITIONAL, null, msgs);
      msgs = basicSetConditional(newConditional, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ELEMENT_BUILD__CONDITIONAL, newConditional, newConditional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ELEMENT_BUILD__VARIABLE_D:
        return basicSetVariableD(null, msgs);
      case MyDslPackage.ELEMENT_BUILD__PAGE:
        return basicSetPage(null, msgs);
      case MyDslPackage.ELEMENT_BUILD__LOOP:
        return basicSetLoop(null, msgs);
      case MyDslPackage.ELEMENT_BUILD__CONDITIONAL:
        return basicSetConditional(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ELEMENT_BUILD__VARIABLE_D:
        return getVariableD();
      case MyDslPackage.ELEMENT_BUILD__PAGE:
        return getPage();
      case MyDslPackage.ELEMENT_BUILD__LOOP:
        return getLoop();
      case MyDslPackage.ELEMENT_BUILD__CONDITIONAL:
        return getConditional();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ELEMENT_BUILD__VARIABLE_D:
        setVariableD((VariableD)newValue);
        return;
      case MyDslPackage.ELEMENT_BUILD__PAGE:
        setPage((Page)newValue);
        return;
      case MyDslPackage.ELEMENT_BUILD__LOOP:
        setLoop((Loop)newValue);
        return;
      case MyDslPackage.ELEMENT_BUILD__CONDITIONAL:
        setConditional((Conditional)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ELEMENT_BUILD__VARIABLE_D:
        setVariableD((VariableD)null);
        return;
      case MyDslPackage.ELEMENT_BUILD__PAGE:
        setPage((Page)null);
        return;
      case MyDslPackage.ELEMENT_BUILD__LOOP:
        setLoop((Loop)null);
        return;
      case MyDslPackage.ELEMENT_BUILD__CONDITIONAL:
        setConditional((Conditional)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ELEMENT_BUILD__VARIABLE_D:
        return variableD != null;
      case MyDslPackage.ELEMENT_BUILD__PAGE:
        return page != null;
      case MyDslPackage.ELEMENT_BUILD__LOOP:
        return loop != null;
      case MyDslPackage.ELEMENT_BUILD__CONDITIONAL:
        return conditional != null;
    }
    return super.eIsSet(featureID);
  }

} //ElementBuildImpl
