/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Float</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.FloatImpl#getFirstInt <em>First Int</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.FloatImpl#getSecondInt <em>Second Int</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FloatImpl extends MinimalEObjectImpl.Container implements org.xtext.example.myDsl.Float
{
  /**
   * The default value of the '{@link #getFirstInt() <em>First Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstInt()
   * @generated
   * @ordered
   */
  protected static final int FIRST_INT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFirstInt() <em>First Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstInt()
   * @generated
   * @ordered
   */
  protected int firstInt = FIRST_INT_EDEFAULT;

  /**
   * The default value of the '{@link #getSecondInt() <em>Second Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecondInt()
   * @generated
   * @ordered
   */
  protected static final int SECOND_INT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSecondInt() <em>Second Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecondInt()
   * @generated
   * @ordered
   */
  protected int secondInt = SECOND_INT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FloatImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FLOAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFirstInt()
  {
    return firstInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirstInt(int newFirstInt)
  {
    int oldFirstInt = firstInt;
    firstInt = newFirstInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FLOAT__FIRST_INT, oldFirstInt, firstInt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSecondInt()
  {
    return secondInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSecondInt(int newSecondInt)
  {
    int oldSecondInt = secondInt;
    secondInt = newSecondInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FLOAT__SECOND_INT, oldSecondInt, secondInt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FLOAT__FIRST_INT:
        return getFirstInt();
      case MyDslPackage.FLOAT__SECOND_INT:
        return getSecondInt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FLOAT__FIRST_INT:
        setFirstInt((Integer)newValue);
        return;
      case MyDslPackage.FLOAT__SECOND_INT:
        setSecondInt((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FLOAT__FIRST_INT:
        setFirstInt(FIRST_INT_EDEFAULT);
        return;
      case MyDslPackage.FLOAT__SECOND_INT:
        setSecondInt(SECOND_INT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FLOAT__FIRST_INT:
        return firstInt != FIRST_INT_EDEFAULT;
      case MyDslPackage.FLOAT__SECOND_INT:
        return secondInt != SECOND_INT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (firstInt: ");
    result.append(firstInt);
    result.append(", secondInt: ");
    result.append(secondInt);
    result.append(')');
    return result.toString();
  }

} //FloatImpl
