/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.Colspan;
import org.xtext.example.myDsl.Fusion;
import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.Rowspan;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fusion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.FusionImpl#getColspan <em>Colspan</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.FusionImpl#getRowspan <em>Rowspan</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FusionImpl extends MinimalEObjectImpl.Container implements Fusion
{
  /**
   * The cached value of the '{@link #getColspan() <em>Colspan</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColspan()
   * @generated
   * @ordered
   */
  protected Colspan colspan;

  /**
   * The cached value of the '{@link #getRowspan() <em>Rowspan</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRowspan()
   * @generated
   * @ordered
   */
  protected Rowspan rowspan;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FusionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FUSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Colspan getColspan()
  {
    return colspan;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColspan(Colspan newColspan, NotificationChain msgs)
  {
    Colspan oldColspan = colspan;
    colspan = newColspan;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FUSION__COLSPAN, oldColspan, newColspan);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColspan(Colspan newColspan)
  {
    if (newColspan != colspan)
    {
      NotificationChain msgs = null;
      if (colspan != null)
        msgs = ((InternalEObject)colspan).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUSION__COLSPAN, null, msgs);
      if (newColspan != null)
        msgs = ((InternalEObject)newColspan).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUSION__COLSPAN, null, msgs);
      msgs = basicSetColspan(newColspan, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FUSION__COLSPAN, newColspan, newColspan));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rowspan getRowspan()
  {
    return rowspan;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRowspan(Rowspan newRowspan, NotificationChain msgs)
  {
    Rowspan oldRowspan = rowspan;
    rowspan = newRowspan;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FUSION__ROWSPAN, oldRowspan, newRowspan);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRowspan(Rowspan newRowspan)
  {
    if (newRowspan != rowspan)
    {
      NotificationChain msgs = null;
      if (rowspan != null)
        msgs = ((InternalEObject)rowspan).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUSION__ROWSPAN, null, msgs);
      if (newRowspan != null)
        msgs = ((InternalEObject)newRowspan).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUSION__ROWSPAN, null, msgs);
      msgs = basicSetRowspan(newRowspan, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FUSION__ROWSPAN, newRowspan, newRowspan));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.FUSION__COLSPAN:
        return basicSetColspan(null, msgs);
      case MyDslPackage.FUSION__ROWSPAN:
        return basicSetRowspan(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FUSION__COLSPAN:
        return getColspan();
      case MyDslPackage.FUSION__ROWSPAN:
        return getRowspan();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FUSION__COLSPAN:
        setColspan((Colspan)newValue);
        return;
      case MyDslPackage.FUSION__ROWSPAN:
        setRowspan((Rowspan)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUSION__COLSPAN:
        setColspan((Colspan)null);
        return;
      case MyDslPackage.FUSION__ROWSPAN:
        setRowspan((Rowspan)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUSION__COLSPAN:
        return colspan != null;
      case MyDslPackage.FUSION__ROWSPAN:
        return rowspan != null;
    }
    return super.eIsSet(featureID);
  }

} //FusionImpl
