/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.SingleExtension;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Extension</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.SingleExtensionImpl#getXlsx <em>Xlsx</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.SingleExtensionImpl#getHtml <em>Html</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.SingleExtensionImpl#getPdf <em>Pdf</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.SingleExtensionImpl#getDoc <em>Doc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleExtensionImpl extends MinimalEObjectImpl.Container implements SingleExtension
{
  /**
   * The default value of the '{@link #getXlsx() <em>Xlsx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXlsx()
   * @generated
   * @ordered
   */
  protected static final String XLSX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getXlsx() <em>Xlsx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXlsx()
   * @generated
   * @ordered
   */
  protected String xlsx = XLSX_EDEFAULT;

  /**
   * The default value of the '{@link #getHtml() <em>Html</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtml()
   * @generated
   * @ordered
   */
  protected static final String HTML_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHtml() <em>Html</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtml()
   * @generated
   * @ordered
   */
  protected String html = HTML_EDEFAULT;

  /**
   * The default value of the '{@link #getPdf() <em>Pdf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPdf()
   * @generated
   * @ordered
   */
  protected static final String PDF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPdf() <em>Pdf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPdf()
   * @generated
   * @ordered
   */
  protected String pdf = PDF_EDEFAULT;

  /**
   * The default value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected static final String DOC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected String doc = DOC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleExtensionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SINGLE_EXTENSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getXlsx()
  {
    return xlsx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setXlsx(String newXlsx)
  {
    String oldXlsx = xlsx;
    xlsx = newXlsx;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_EXTENSION__XLSX, oldXlsx, xlsx));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHtml()
  {
    return html;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHtml(String newHtml)
  {
    String oldHtml = html;
    html = newHtml;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_EXTENSION__HTML, oldHtml, html));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPdf()
  {
    return pdf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPdf(String newPdf)
  {
    String oldPdf = pdf;
    pdf = newPdf;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_EXTENSION__PDF, oldPdf, pdf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDoc()
  {
    return doc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDoc(String newDoc)
  {
    String oldDoc = doc;
    doc = newDoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SINGLE_EXTENSION__DOC, oldDoc, doc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_EXTENSION__XLSX:
        return getXlsx();
      case MyDslPackage.SINGLE_EXTENSION__HTML:
        return getHtml();
      case MyDslPackage.SINGLE_EXTENSION__PDF:
        return getPdf();
      case MyDslPackage.SINGLE_EXTENSION__DOC:
        return getDoc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_EXTENSION__XLSX:
        setXlsx((String)newValue);
        return;
      case MyDslPackage.SINGLE_EXTENSION__HTML:
        setHtml((String)newValue);
        return;
      case MyDslPackage.SINGLE_EXTENSION__PDF:
        setPdf((String)newValue);
        return;
      case MyDslPackage.SINGLE_EXTENSION__DOC:
        setDoc((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_EXTENSION__XLSX:
        setXlsx(XLSX_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_EXTENSION__HTML:
        setHtml(HTML_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_EXTENSION__PDF:
        setPdf(PDF_EDEFAULT);
        return;
      case MyDslPackage.SINGLE_EXTENSION__DOC:
        setDoc(DOC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SINGLE_EXTENSION__XLSX:
        return XLSX_EDEFAULT == null ? xlsx != null : !XLSX_EDEFAULT.equals(xlsx);
      case MyDslPackage.SINGLE_EXTENSION__HTML:
        return HTML_EDEFAULT == null ? html != null : !HTML_EDEFAULT.equals(html);
      case MyDslPackage.SINGLE_EXTENSION__PDF:
        return PDF_EDEFAULT == null ? pdf != null : !PDF_EDEFAULT.equals(pdf);
      case MyDslPackage.SINGLE_EXTENSION__DOC:
        return DOC_EDEFAULT == null ? doc != null : !DOC_EDEFAULT.equals(doc);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (xlsx: ");
    result.append(xlsx);
    result.append(", html: ");
    result.append(html);
    result.append(", pdf: ");
    result.append(pdf);
    result.append(", doc: ");
    result.append(doc);
    result.append(')');
    return result.toString();
  }

} //SingleExtensionImpl
