/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.myDsl.ClassVariable;
import org.xtext.example.myDsl.Function;
import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.SuperVariable;
import org.xtext.example.myDsl.Value;
import org.xtext.example.myDsl.VariableD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable D</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.VariableDImpl#getSuperVariable <em>Super Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.VariableDImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.VariableDImpl#getClassVariable <em>Class Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.VariableDImpl#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VariableDImpl extends MinimalEObjectImpl.Container implements VariableD
{
  /**
   * The cached value of the '{@link #getSuperVariable() <em>Super Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperVariable()
   * @generated
   * @ordered
   */
  protected SuperVariable superVariable;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected Value value;

  /**
   * The cached value of the '{@link #getClassVariable() <em>Class Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassVariable()
   * @generated
   * @ordered
   */
  protected ClassVariable classVariable;

  /**
   * The cached value of the '{@link #getFunction() <em>Function</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunction()
   * @generated
   * @ordered
   */
  protected EList<Function> function;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VARIABLE_D;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SuperVariable getSuperVariable()
  {
    return superVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSuperVariable(SuperVariable newSuperVariable, NotificationChain msgs)
  {
    SuperVariable oldSuperVariable = superVariable;
    superVariable = newSuperVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__SUPER_VARIABLE, oldSuperVariable, newSuperVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperVariable(SuperVariable newSuperVariable)
  {
    if (newSuperVariable != superVariable)
    {
      NotificationChain msgs = null;
      if (superVariable != null)
        msgs = ((InternalEObject)superVariable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__SUPER_VARIABLE, null, msgs);
      if (newSuperVariable != null)
        msgs = ((InternalEObject)newSuperVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__SUPER_VARIABLE, null, msgs);
      msgs = basicSetSuperVariable(newSuperVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__SUPER_VARIABLE, newSuperVariable, newSuperVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Value getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(Value newValue, NotificationChain msgs)
  {
    Value oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(Value newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassVariable getClassVariable()
  {
    return classVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClassVariable(ClassVariable newClassVariable, NotificationChain msgs)
  {
    ClassVariable oldClassVariable = classVariable;
    classVariable = newClassVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__CLASS_VARIABLE, oldClassVariable, newClassVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClassVariable(ClassVariable newClassVariable)
  {
    if (newClassVariable != classVariable)
    {
      NotificationChain msgs = null;
      if (classVariable != null)
        msgs = ((InternalEObject)classVariable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__CLASS_VARIABLE, null, msgs);
      if (newClassVariable != null)
        msgs = ((InternalEObject)newClassVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VARIABLE_D__CLASS_VARIABLE, null, msgs);
      msgs = basicSetClassVariable(newClassVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VARIABLE_D__CLASS_VARIABLE, newClassVariable, newClassVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Function> getFunction()
  {
    if (function == null)
    {
      function = new EObjectContainmentEList<Function>(Function.class, this, MyDslPackage.VARIABLE_D__FUNCTION);
    }
    return function;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.VARIABLE_D__SUPER_VARIABLE:
        return basicSetSuperVariable(null, msgs);
      case MyDslPackage.VARIABLE_D__VALUE:
        return basicSetValue(null, msgs);
      case MyDslPackage.VARIABLE_D__CLASS_VARIABLE:
        return basicSetClassVariable(null, msgs);
      case MyDslPackage.VARIABLE_D__FUNCTION:
        return ((InternalEList<?>)getFunction()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VARIABLE_D__SUPER_VARIABLE:
        return getSuperVariable();
      case MyDslPackage.VARIABLE_D__VALUE:
        return getValue();
      case MyDslPackage.VARIABLE_D__CLASS_VARIABLE:
        return getClassVariable();
      case MyDslPackage.VARIABLE_D__FUNCTION:
        return getFunction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VARIABLE_D__SUPER_VARIABLE:
        setSuperVariable((SuperVariable)newValue);
        return;
      case MyDslPackage.VARIABLE_D__VALUE:
        setValue((Value)newValue);
        return;
      case MyDslPackage.VARIABLE_D__CLASS_VARIABLE:
        setClassVariable((ClassVariable)newValue);
        return;
      case MyDslPackage.VARIABLE_D__FUNCTION:
        getFunction().clear();
        getFunction().addAll((Collection<? extends Function>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VARIABLE_D__SUPER_VARIABLE:
        setSuperVariable((SuperVariable)null);
        return;
      case MyDslPackage.VARIABLE_D__VALUE:
        setValue((Value)null);
        return;
      case MyDslPackage.VARIABLE_D__CLASS_VARIABLE:
        setClassVariable((ClassVariable)null);
        return;
      case MyDslPackage.VARIABLE_D__FUNCTION:
        getFunction().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VARIABLE_D__SUPER_VARIABLE:
        return superVariable != null;
      case MyDslPackage.VARIABLE_D__VALUE:
        return value != null;
      case MyDslPackage.VARIABLE_D__CLASS_VARIABLE:
        return classVariable != null;
      case MyDslPackage.VARIABLE_D__FUNCTION:
        return function != null && !function.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //VariableDImpl
