/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.myDsl.ArrayC;
import org.xtext.example.myDsl.MyDslPackage;
import org.xtext.example.myDsl.ObjectC;
import org.xtext.example.myDsl.OtherElement;
import org.xtext.example.myDsl.Variable;
import org.xtext.example.myDsl.With;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>With</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.impl.WithImpl#getInit <em>Init</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.WithImpl#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.WithImpl#getObjectC <em>Object C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.WithImpl#getArrayC <em>Array C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.impl.WithImpl#getOtherElement <em>Other Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WithImpl extends MinimalEObjectImpl.Container implements With
{
  /**
   * The cached value of the '{@link #getInit() <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit()
   * @generated
   * @ordered
   */
  protected Variable init;

  /**
   * The cached value of the '{@link #getVariable() <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable()
   * @generated
   * @ordered
   */
  protected Variable variable;

  /**
   * The cached value of the '{@link #getObjectC() <em>Object C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectC()
   * @generated
   * @ordered
   */
  protected ObjectC objectC;

  /**
   * The cached value of the '{@link #getArrayC() <em>Array C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrayC()
   * @generated
   * @ordered
   */
  protected ArrayC arrayC;

  /**
   * The cached value of the '{@link #getOtherElement() <em>Other Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOtherElement()
   * @generated
   * @ordered
   */
  protected EList<OtherElement> otherElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WithImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.WITH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable getInit()
  {
    return init;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit(Variable newInit, NotificationChain msgs)
  {
    Variable oldInit = init;
    init = newInit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__INIT, oldInit, newInit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInit(Variable newInit)
  {
    if (newInit != init)
    {
      NotificationChain msgs = null;
      if (init != null)
        msgs = ((InternalEObject)init).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__INIT, null, msgs);
      if (newInit != null)
        msgs = ((InternalEObject)newInit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__INIT, null, msgs);
      msgs = basicSetInit(newInit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__INIT, newInit, newInit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable getVariable()
  {
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariable(Variable newVariable, NotificationChain msgs)
  {
    Variable oldVariable = variable;
    variable = newVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__VARIABLE, oldVariable, newVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariable(Variable newVariable)
  {
    if (newVariable != variable)
    {
      NotificationChain msgs = null;
      if (variable != null)
        msgs = ((InternalEObject)variable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__VARIABLE, null, msgs);
      if (newVariable != null)
        msgs = ((InternalEObject)newVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__VARIABLE, null, msgs);
      msgs = basicSetVariable(newVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__VARIABLE, newVariable, newVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObjectC getObjectC()
  {
    return objectC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObjectC(ObjectC newObjectC, NotificationChain msgs)
  {
    ObjectC oldObjectC = objectC;
    objectC = newObjectC;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__OBJECT_C, oldObjectC, newObjectC);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObjectC(ObjectC newObjectC)
  {
    if (newObjectC != objectC)
    {
      NotificationChain msgs = null;
      if (objectC != null)
        msgs = ((InternalEObject)objectC).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__OBJECT_C, null, msgs);
      if (newObjectC != null)
        msgs = ((InternalEObject)newObjectC).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__OBJECT_C, null, msgs);
      msgs = basicSetObjectC(newObjectC, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__OBJECT_C, newObjectC, newObjectC));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArrayC getArrayC()
  {
    return arrayC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetArrayC(ArrayC newArrayC, NotificationChain msgs)
  {
    ArrayC oldArrayC = arrayC;
    arrayC = newArrayC;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__ARRAY_C, oldArrayC, newArrayC);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArrayC(ArrayC newArrayC)
  {
    if (newArrayC != arrayC)
    {
      NotificationChain msgs = null;
      if (arrayC != null)
        msgs = ((InternalEObject)arrayC).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__ARRAY_C, null, msgs);
      if (newArrayC != null)
        msgs = ((InternalEObject)newArrayC).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.WITH__ARRAY_C, null, msgs);
      msgs = basicSetArrayC(newArrayC, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WITH__ARRAY_C, newArrayC, newArrayC));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<OtherElement> getOtherElement()
  {
    if (otherElement == null)
    {
      otherElement = new EObjectContainmentEList<OtherElement>(OtherElement.class, this, MyDslPackage.WITH__OTHER_ELEMENT);
    }
    return otherElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.WITH__INIT:
        return basicSetInit(null, msgs);
      case MyDslPackage.WITH__VARIABLE:
        return basicSetVariable(null, msgs);
      case MyDslPackage.WITH__OBJECT_C:
        return basicSetObjectC(null, msgs);
      case MyDslPackage.WITH__ARRAY_C:
        return basicSetArrayC(null, msgs);
      case MyDslPackage.WITH__OTHER_ELEMENT:
        return ((InternalEList<?>)getOtherElement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.WITH__INIT:
        return getInit();
      case MyDslPackage.WITH__VARIABLE:
        return getVariable();
      case MyDslPackage.WITH__OBJECT_C:
        return getObjectC();
      case MyDslPackage.WITH__ARRAY_C:
        return getArrayC();
      case MyDslPackage.WITH__OTHER_ELEMENT:
        return getOtherElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.WITH__INIT:
        setInit((Variable)newValue);
        return;
      case MyDslPackage.WITH__VARIABLE:
        setVariable((Variable)newValue);
        return;
      case MyDslPackage.WITH__OBJECT_C:
        setObjectC((ObjectC)newValue);
        return;
      case MyDslPackage.WITH__ARRAY_C:
        setArrayC((ArrayC)newValue);
        return;
      case MyDslPackage.WITH__OTHER_ELEMENT:
        getOtherElement().clear();
        getOtherElement().addAll((Collection<? extends OtherElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WITH__INIT:
        setInit((Variable)null);
        return;
      case MyDslPackage.WITH__VARIABLE:
        setVariable((Variable)null);
        return;
      case MyDslPackage.WITH__OBJECT_C:
        setObjectC((ObjectC)null);
        return;
      case MyDslPackage.WITH__ARRAY_C:
        setArrayC((ArrayC)null);
        return;
      case MyDslPackage.WITH__OTHER_ELEMENT:
        getOtherElement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WITH__INIT:
        return init != null;
      case MyDslPackage.WITH__VARIABLE:
        return variable != null;
      case MyDslPackage.WITH__OBJECT_C:
        return objectC != null;
      case MyDslPackage.WITH__ARRAY_C:
        return arrayC != null;
      case MyDslPackage.WITH__OTHER_ELEMENT:
        return otherElement != null && !otherElement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //WithImpl
