/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Col</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Col#getFusion <em>Fusion</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getImg <em>Img</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getObjectC <em>Object C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getArrayC <em>Array C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getVariableD <em>Variable D</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getInteger <em>Integer</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getFloatValue <em>Float Value</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getFunction <em>Function</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Col#getClassD <em>Class D</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getCol()
 * @model
 * @generated
 */
public interface Col extends EObject
{
  /**
   * Returns the value of the '<em><b>Fusion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fusion</em>' containment reference.
   * @see #setFusion(Fusion)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_Fusion()
   * @model containment="true"
   * @generated
   */
  Fusion getFusion();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getFusion <em>Fusion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fusion</em>' containment reference.
   * @see #getFusion()
   * @generated
   */
  void setFusion(Fusion value);

  /**
   * Returns the value of the '<em><b>Img</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Img</em>' containment reference.
   * @see #setImg(Img)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_Img()
   * @model containment="true"
   * @generated
   */
  Img getImg();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getImg <em>Img</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Img</em>' containment reference.
   * @see #getImg()
   * @generated
   */
  void setImg(Img value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Variable)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_Variable()
   * @model containment="true"
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Object C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object C</em>' containment reference.
   * @see #setObjectC(ObjectC)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_ObjectC()
   * @model containment="true"
   * @generated
   */
  ObjectC getObjectC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getObjectC <em>Object C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object C</em>' containment reference.
   * @see #getObjectC()
   * @generated
   */
  void setObjectC(ObjectC value);

  /**
   * Returns the value of the '<em><b>Array C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array C</em>' containment reference.
   * @see #setArrayC(ArrayC)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_ArrayC()
   * @model containment="true"
   * @generated
   */
  ArrayC getArrayC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getArrayC <em>Array C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array C</em>' containment reference.
   * @see #getArrayC()
   * @generated
   */
  void setArrayC(ArrayC value);

  /**
   * Returns the value of the '<em><b>Variable D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable D</em>' containment reference.
   * @see #setVariableD(VariableD)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_VariableD()
   * @model containment="true"
   * @generated
   */
  VariableD getVariableD();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getVariableD <em>Variable D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable D</em>' containment reference.
   * @see #getVariableD()
   * @generated
   */
  void setVariableD(VariableD value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer</em>' attribute.
   * @see #setInteger(int)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_Integer()
   * @model
   * @generated
   */
  int getInteger();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getInteger <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer</em>' attribute.
   * @see #getInteger()
   * @generated
   */
  void setInteger(int value);

  /**
   * Returns the value of the '<em><b>Float Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float Value</em>' containment reference.
   * @see #setFloatValue(org.xtext.example.myDsl.Float)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_FloatValue()
   * @model containment="true"
   * @generated
   */
  org.xtext.example.myDsl.Float getFloatValue();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getFloatValue <em>Float Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float Value</em>' containment reference.
   * @see #getFloatValue()
   * @generated
   */
  void setFloatValue(org.xtext.example.myDsl.Float value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(Function)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_Function()
   * @model containment="true"
   * @generated
   */
  Function getFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(Function value);

  /**
   * Returns the value of the '<em><b>Class D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class D</em>' containment reference.
   * @see #setClassD(ClassD)
   * @see org.xtext.example.myDsl.MyDslPackage#getCol_ClassD()
   * @model containment="true"
   * @generated
   */
  ClassD getClassD();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Col#getClassD <em>Class D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class D</em>' containment reference.
   * @see #getClassD()
   * @generated
   */
  void setClassD(ClassD value);

} // Col
