/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Css Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getInteger <em>Integer</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getComa <em>Coma</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getApostrophe <em>Apostrophe</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getHashtag <em>Hashtag</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.CssValue#getPourcent <em>Pourcent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getCssValue()
 * @model
 * @generated
 */
public interface CssValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer</em>' attribute.
   * @see #setInteger(int)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Integer()
   * @model
   * @generated
   */
  int getInteger();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getInteger <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer</em>' attribute.
   * @see #getInteger()
   * @generated
   */
  void setInteger(int value);

  /**
   * Returns the value of the '<em><b>Coma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coma</em>' attribute.
   * @see #setComa(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Coma()
   * @model
   * @generated
   */
  String getComa();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getComa <em>Coma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coma</em>' attribute.
   * @see #getComa()
   * @generated
   */
  void setComa(String value);

  /**
   * Returns the value of the '<em><b>Apostrophe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apostrophe</em>' attribute.
   * @see #setApostrophe(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Apostrophe()
   * @model
   * @generated
   */
  String getApostrophe();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getApostrophe <em>Apostrophe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apostrophe</em>' attribute.
   * @see #getApostrophe()
   * @generated
   */
  void setApostrophe(String value);

  /**
   * Returns the value of the '<em><b>Hashtag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hashtag</em>' attribute.
   * @see #setHashtag(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Hashtag()
   * @model
   * @generated
   */
  String getHashtag();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getHashtag <em>Hashtag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hashtag</em>' attribute.
   * @see #getHashtag()
   * @generated
   */
  void setHashtag(String value);

  /**
   * Returns the value of the '<em><b>Pourcent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pourcent</em>' attribute.
   * @see #setPourcent(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getCssValue_Pourcent()
   * @model
   * @generated
   */
  String getPourcent();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.CssValue#getPourcent <em>Pourcent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pourcent</em>' attribute.
   * @see #getPourcent()
   * @generated
   */
  void setPourcent(String value);

} // CssValue
