/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Document#getData <em>Data</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Document#getBuild <em>Build</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Document#getStyle <em>Style</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(Data)
   * @see org.xtext.example.myDsl.MyDslPackage#getDocument_Data()
   * @model containment="true"
   * @generated
   */
  Data getData();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Document#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(Data value);

  /**
   * Returns the value of the '<em><b>Build</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Build</em>' containment reference.
   * @see #setBuild(Build)
   * @see org.xtext.example.myDsl.MyDslPackage#getDocument_Build()
   * @model containment="true"
   * @generated
   */
  Build getBuild();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Document#getBuild <em>Build</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Build</em>' containment reference.
   * @see #getBuild()
   * @generated
   */
  void setBuild(Build value);

  /**
   * Returns the value of the '<em><b>Style</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' containment reference.
   * @see #setStyle(Style)
   * @see org.xtext.example.myDsl.MyDslPackage#getDocument_Style()
   * @model containment="true"
   * @generated
   */
  Style getStyle();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Document#getStyle <em>Style</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' containment reference.
   * @see #getStyle()
   * @generated
   */
  void setStyle(Style value);

} // Document
