/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.ElementRow#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.ElementRow#getVariableD <em>Variable D</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.ElementRow#getCol <em>Col</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.ElementRow#getConditional <em>Conditional</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.ElementRow#getLoop <em>Loop</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getElementRow()
 * @model
 * @generated
 */
public interface ElementRow extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Variable)
   * @see org.xtext.example.myDsl.MyDslPackage#getElementRow_Variable()
   * @model containment="true"
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.ElementRow#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Variable D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable D</em>' containment reference.
   * @see #setVariableD(VariableD)
   * @see org.xtext.example.myDsl.MyDslPackage#getElementRow_VariableD()
   * @model containment="true"
   * @generated
   */
  VariableD getVariableD();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.ElementRow#getVariableD <em>Variable D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable D</em>' containment reference.
   * @see #getVariableD()
   * @generated
   */
  void setVariableD(VariableD value);

  /**
   * Returns the value of the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' containment reference.
   * @see #setCol(Col)
   * @see org.xtext.example.myDsl.MyDslPackage#getElementRow_Col()
   * @model containment="true"
   * @generated
   */
  Col getCol();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.ElementRow#getCol <em>Col</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' containment reference.
   * @see #getCol()
   * @generated
   */
  void setCol(Col value);

  /**
   * Returns the value of the '<em><b>Conditional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional</em>' containment reference.
   * @see #setConditional(Conditional)
   * @see org.xtext.example.myDsl.MyDslPackage#getElementRow_Conditional()
   * @model containment="true"
   * @generated
   */
  Conditional getConditional();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.ElementRow#getConditional <em>Conditional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional</em>' containment reference.
   * @see #getConditional()
   * @generated
   */
  void setConditional(Conditional value);

  /**
   * Returns the value of the '<em><b>Loop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop</em>' containment reference.
   * @see #setLoop(Loop)
   * @see org.xtext.example.myDsl.MyDslPackage#getElementRow_Loop()
   * @model containment="true"
   * @generated
   */
  Loop getLoop();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.ElementRow#getLoop <em>Loop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop</em>' containment reference.
   * @see #getLoop()
   * @generated
   */
  void setLoop(Loop value);

} // ElementRow
