/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Function#getSumFunction <em>Sum Function</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Function#getProdFunction <em>Prod Function</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Function#getDivFunction <em>Div Function</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
  /**
   * Returns the value of the '<em><b>Sum Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sum Function</em>' containment reference.
   * @see #setSumFunction(SumFunction)
   * @see org.xtext.example.myDsl.MyDslPackage#getFunction_SumFunction()
   * @model containment="true"
   * @generated
   */
  SumFunction getSumFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Function#getSumFunction <em>Sum Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sum Function</em>' containment reference.
   * @see #getSumFunction()
   * @generated
   */
  void setSumFunction(SumFunction value);

  /**
   * Returns the value of the '<em><b>Prod Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prod Function</em>' containment reference.
   * @see #setProdFunction(ProdFunction)
   * @see org.xtext.example.myDsl.MyDslPackage#getFunction_ProdFunction()
   * @model containment="true"
   * @generated
   */
  ProdFunction getProdFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Function#getProdFunction <em>Prod Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prod Function</em>' containment reference.
   * @see #getProdFunction()
   * @generated
   */
  void setProdFunction(ProdFunction value);

  /**
   * Returns the value of the '<em><b>Div Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Div Function</em>' containment reference.
   * @see #setDivFunction(DivFunction)
   * @see org.xtext.example.myDsl.MyDslPackage#getFunction_DivFunction()
   * @model containment="true"
   * @generated
   */
  DivFunction getDivFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Function#getDivFunction <em>Div Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Div Function</em>' containment reference.
   * @see #getDivFunction()
   * @generated
   */
  void setDivFunction(DivFunction value);

} // Function
