/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Img</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Img#getClassD <em>Class D</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Img#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Img#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Img#getObjectC <em>Object C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Img#getArrayC <em>Array C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Img#getStringAlt <em>String Alt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getImg()
 * @model
 * @generated
 */
public interface Img extends EObject
{
  /**
   * Returns the value of the '<em><b>Class D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class D</em>' containment reference.
   * @see #setClassD(ClassD)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_ClassD()
   * @model containment="true"
   * @generated
   */
  ClassD getClassD();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getClassD <em>Class D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class D</em>' containment reference.
   * @see #getClassD()
   * @generated
   */
  void setClassD(ClassD value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Variable)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_Variable()
   * @model containment="true"
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Object C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object C</em>' containment reference.
   * @see #setObjectC(ObjectC)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_ObjectC()
   * @model containment="true"
   * @generated
   */
  ObjectC getObjectC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getObjectC <em>Object C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object C</em>' containment reference.
   * @see #getObjectC()
   * @generated
   */
  void setObjectC(ObjectC value);

  /**
   * Returns the value of the '<em><b>Array C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array C</em>' containment reference.
   * @see #setArrayC(ArrayC)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_ArrayC()
   * @model containment="true"
   * @generated
   */
  ArrayC getArrayC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getArrayC <em>Array C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array C</em>' containment reference.
   * @see #getArrayC()
   * @generated
   */
  void setArrayC(ArrayC value);

  /**
   * Returns the value of the '<em><b>String Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Alt</em>' attribute.
   * @see #setStringAlt(String)
   * @see org.xtext.example.myDsl.MyDslPackage#getImg_StringAlt()
   * @model
   * @generated
   */
  String getStringAlt();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Img#getStringAlt <em>String Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Alt</em>' attribute.
   * @see #getStringAlt()
   * @generated
   */
  void setStringAlt(String value);

} // Img
