/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.OtherElement#getPage <em>Page</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.OtherElement#getRow <em>Row</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.OtherElement#getCol <em>Col</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.OtherElement#getLoop <em>Loop</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.OtherElement#getConditional <em>Conditional</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement()
 * @model
 * @generated
 */
public interface OtherElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Page</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Page</em>' containment reference.
   * @see #setPage(Page)
   * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement_Page()
   * @model containment="true"
   * @generated
   */
  Page getPage();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.OtherElement#getPage <em>Page</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Page</em>' containment reference.
   * @see #getPage()
   * @generated
   */
  void setPage(Page value);

  /**
   * Returns the value of the '<em><b>Row</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' containment reference.
   * @see #setRow(Row)
   * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement_Row()
   * @model containment="true"
   * @generated
   */
  Row getRow();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.OtherElement#getRow <em>Row</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' containment reference.
   * @see #getRow()
   * @generated
   */
  void setRow(Row value);

  /**
   * Returns the value of the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' containment reference.
   * @see #setCol(Col)
   * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement_Col()
   * @model containment="true"
   * @generated
   */
  Col getCol();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.OtherElement#getCol <em>Col</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' containment reference.
   * @see #getCol()
   * @generated
   */
  void setCol(Col value);

  /**
   * Returns the value of the '<em><b>Loop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop</em>' containment reference.
   * @see #setLoop(Loop)
   * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement_Loop()
   * @model containment="true"
   * @generated
   */
  Loop getLoop();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.OtherElement#getLoop <em>Loop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop</em>' containment reference.
   * @see #getLoop()
   * @generated
   */
  void setLoop(Loop value);

  /**
   * Returns the value of the '<em><b>Conditional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional</em>' containment reference.
   * @see #setConditional(Conditional)
   * @see org.xtext.example.myDsl.MyDslPackage#getOtherElement_Conditional()
   * @model containment="true"
   * @generated
   */
  Conditional getConditional();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.OtherElement#getConditional <em>Conditional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional</em>' containment reference.
   * @see #getConditional()
   * @generated
   */
  void setConditional(Conditional value);

} // OtherElement
