/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Style</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Style#getCss <em>Css</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getStyle()
 * @model
 * @generated
 */
public interface Style extends EObject
{
  /**
   * Returns the value of the '<em><b>Css</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Css</em>' containment reference.
   * @see #setCss(Css)
   * @see org.xtext.example.myDsl.MyDslPackage#getStyle_Css()
   * @model containment="true"
   * @generated
   */
  Css getCss();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Style#getCss <em>Css</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Css</em>' containment reference.
   * @see #getCss()
   * @generated
   */
  void setCss(Css value);

} // Style
