/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.Title#getBigTitle <em>Big Title</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Title#getSubTitle <em>Sub Title</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.Title#getSubSubTitle <em>Sub Sub Title</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getTitle()
 * @model
 * @generated
 */
public interface Title extends EObject
{
  /**
   * Returns the value of the '<em><b>Big Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Big Title</em>' containment reference.
   * @see #setBigTitle(BigTitle)
   * @see org.xtext.example.myDsl.MyDslPackage#getTitle_BigTitle()
   * @model containment="true"
   * @generated
   */
  BigTitle getBigTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Title#getBigTitle <em>Big Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Big Title</em>' containment reference.
   * @see #getBigTitle()
   * @generated
   */
  void setBigTitle(BigTitle value);

  /**
   * Returns the value of the '<em><b>Sub Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Title</em>' containment reference.
   * @see #setSubTitle(SubTitle)
   * @see org.xtext.example.myDsl.MyDslPackage#getTitle_SubTitle()
   * @model containment="true"
   * @generated
   */
  SubTitle getSubTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Title#getSubTitle <em>Sub Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Title</em>' containment reference.
   * @see #getSubTitle()
   * @generated
   */
  void setSubTitle(SubTitle value);

  /**
   * Returns the value of the '<em><b>Sub Sub Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Sub Title</em>' containment reference.
   * @see #setSubSubTitle(SubSubTitle)
   * @see org.xtext.example.myDsl.MyDslPackage#getTitle_SubSubTitle()
   * @model containment="true"
   * @generated
   */
  SubSubTitle getSubSubTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.Title#getSubSubTitle <em>Sub Sub Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Sub Title</em>' containment reference.
   * @see #getSubSubTitle()
   * @generated
   */
  void setSubSubTitle(SubSubTitle value);

} // Title
