/**
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>With</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myDsl.With#getInit <em>Init</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.With#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.With#getObjectC <em>Object C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.With#getArrayC <em>Array C</em>}</li>
 *   <li>{@link org.xtext.example.myDsl.With#getOtherElement <em>Other Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myDsl.MyDslPackage#getWith()
 * @model
 * @generated
 */
public interface With extends EObject
{
  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference.
   * @see #setInit(Variable)
   * @see org.xtext.example.myDsl.MyDslPackage#getWith_Init()
   * @model containment="true"
   * @generated
   */
  Variable getInit();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.With#getInit <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' containment reference.
   * @see #getInit()
   * @generated
   */
  void setInit(Variable value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Variable)
   * @see org.xtext.example.myDsl.MyDslPackage#getWith_Variable()
   * @model containment="true"
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.With#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Object C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object C</em>' containment reference.
   * @see #setObjectC(ObjectC)
   * @see org.xtext.example.myDsl.MyDslPackage#getWith_ObjectC()
   * @model containment="true"
   * @generated
   */
  ObjectC getObjectC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.With#getObjectC <em>Object C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object C</em>' containment reference.
   * @see #getObjectC()
   * @generated
   */
  void setObjectC(ObjectC value);

  /**
   * Returns the value of the '<em><b>Array C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array C</em>' containment reference.
   * @see #setArrayC(ArrayC)
   * @see org.xtext.example.myDsl.MyDslPackage#getWith_ArrayC()
   * @model containment="true"
   * @generated
   */
  ArrayC getArrayC();

  /**
   * Sets the value of the '{@link org.xtext.example.myDsl.With#getArrayC <em>Array C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array C</em>' containment reference.
   * @see #getArrayC()
   * @generated
   */
  void setArrayC(ArrayC value);

  /**
   * Returns the value of the '<em><b>Other Element</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.myDsl.OtherElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other Element</em>' containment reference list.
   * @see org.xtext.example.myDsl.MyDslPackage#getWith_OtherElement()
   * @model containment="true"
   * @generated
   */
  EList<OtherElement> getOtherElement();

} // With
