/*
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGrammarScopeProvider extends DelegatingScopeProvider {
}
