/*
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GrammarRuntimeModule extends AbstractGrammarRuntimeModule {
}
