/*
 * generated by Xtext 2.35.0-SNAPSHOT
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.Grammar.ui.internal.GrammarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GrammarExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GrammarActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GrammarActivator activator = GrammarActivator.getInstance();
		return activator != null ? activator.getInjector(GrammarActivator.ORG_XTEXT_EXAMPLE_GRAMMAR) : null;
	}

}
